//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Forum.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Thread
    {
        public Thread()
        {
            this.Comments = new HashSet<Comment>();
            this.TagThreads = new HashSet<TagThread>();
        }
    
        public int ThreadId { get; set; }
        [Required]
        public string Title { get; set; }
        [Required]
        public string Content { get; set; }
        public string UserName { get; set; }


        [DataType(DataType.DateTime)]
        [DisplayName("Created Date")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yy}")]
        public System.DateTime Date { get; set; }
        public int Views { get; set; }
        public int Upvotes { get; set; }
    
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual ICollection<TagThread> TagThreads { get; set; }
        public virtual User User { get; set; }
    }
}
