//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Forum.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class User
    {
        public User()
        {
            this.Comments = new HashSet<Comment>();
            this.Threads = new HashSet<Thread>();
        }
    
        [Required(ErrorMessage="Please enter a username.") ]
        [Display(Name = "Username")]
        public string UserName { get; set; }

        [Required(ErrorMessage= "Please enter a password.")]
        [MinLength(5, ErrorMessage = "The password must have at least 6 characters.")]
        public string Password { get; set; }

        [Required(ErrorMessage = "Please enter your lastname.")]
        public string LastName { get; set; }

        [Required(ErrorMessage = "Please enter your firstname.")]
        public string FirstName { get; set; }

        [Required(ErrorMessage = "Please enter your email.")]
        [DataType(DataType.EmailAddress)]
        public string Email { get; set; }
        public string City { get; set; }
        public string Country { get; set; }
        public string ImgPath { get; set; }

         [DataType(DataType.MultilineText)]
        public string Interests { get; set; }
    
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual ICollection<Thread> Threads { get; set; }
    }
}
